import type { Metadata } from "next";
import { Mali } from "next/font/google";
import "./globals.css";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

const maliFont = Mali({
	weight: ["200", "300", "400"],
	style: "normal",
	variable: "--mali",
});

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="pt-BR">
			<body
				className={`${maliFont.variable} antialiased`}
				cz-shortcut-listen="true">
				{children}
			</body>
		</html>
	);
}
